name: Build Assets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_PAT }}

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Build
      run: |
        npm ci
        grunt
        
    - name: Commit assets
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'Github'
          git config --global user.email 'cannarocks@users.noreply.github.com'
          git commit -am "chore: executed grunt command"
          git push
        fi 
